#!/bin/bash
# sync-claude-activity.sh — Keep laptop in sync with Mini's Claude coder output
# Runs every 15 min via LaunchAgent. Prevents Codex from redoing Claude's work.
set -euo pipefail

MINI="aaronmontgomerymini@100.69.127.98"
SSH_OPTS="-o ConnectTimeout=5 -o IdentitiesOnly=yes -i $HOME/.ssh/id_ed25519 -o BatchMode=yes"
AAPM_DIR="$HOME/Autonomous-Assignment-Program-Manager"
DIGEST_FILE="$AAPM_DIR/RECENT_ACTIVITY.md"
TODO_FILE="$AAPM_DIR/TODO.md"
LOG_FILE="$HOME/.codex/log/sync-claude.log"
LOCK_FILE="/tmp/sync-claude-activity.lock"

mkdir -p "$(dirname "$LOG_FILE")"

log() { echo "[$(date '+%H:%M:%S')] $1" >> "$LOG_FILE" 2>/dev/null; }

# Lock to prevent overlapping runs
if [ -f "$LOCK_FILE" ]; then
    LOCK_PID=$(cat "$LOCK_FILE" 2>/dev/null)
    if kill -0 "$LOCK_PID" 2>/dev/null; then
        exit 0
    fi
fi
echo $$ > "$LOCK_FILE"
trap 'rm -f "$LOCK_FILE"' EXIT

# Check Mini reachability
if ! ssh $SSH_OPTS "$MINI" 'true' 2>/dev/null; then
    log "Mini unreachable — skipping"
    exit 0
fi

# 1. Fetch completed tasks from coder log (last 24h)
COMPLETED=$(ssh $SSH_OPTS "$MINI" '
    LOG="$HOME/.openclaw/logs/claude-coder.log"
    if [ -f "$LOG" ]; then
        CUTOFF=$(date -v-24H "+%Y-%m-%d" 2>/dev/null || date -d "24 hours ago" "+%Y-%m-%d" 2>/dev/null || echo "2026-01-01")
        grep "Task COMPLETED\|Task FAILED\|Skipping already-completed" "$LOG" 2>/dev/null | while read -r line; do
            LOG_DATE=$(echo "$line" | grep -oE "^\\[([0-9-]+)" | tr -d "[")
            if [[ "$LOG_DATE" > "$CUTOFF" || "$LOG_DATE" == "$CUTOFF" ]]; then
                echo "$line"
            fi
        done
    fi
' 2>/dev/null || echo "")

# 2. Get list of claude/* branches on Mini bare repos
CLAUDE_BRANCHES=$(ssh $SSH_OPTS "$MINI" '
    for repo in ~/repos/personal/aapm.git ~/repos/aapm.git; do
        if [ -d "$repo" ]; then
            git -C "$repo" branch 2>/dev/null | grep "claude/" | sed "s/^..//" | while read -r b; do
                LAST=$(git -C "$repo" log -1 --format="%cd|%s" --date=short "$b" 2>/dev/null)
                echo "aapm|$b|$LAST"
            done
        fi
    done
    for repo in ~/repos/moltbot/*.git ~/repos/personal/*.git; do
        [ -d "$repo" ] || continue
        RNAME=$(basename "$repo" .git)
        git -C "$repo" branch 2>/dev/null | grep "claude/" | sed "s/^..//" | while read -r b; do
            LAST=$(git -C "$repo" log -1 --format="%cd|%s" --date=short "$b" 2>/dev/null)
            echo "$RNAME|$b|$LAST"
        done
    done
' 2>/dev/null || echo "")

# 3. Write digest file
TIMESTAMP=$(date "+%Y-%m-%d %H:%M HST")
cat > "$DIGEST_FILE" << HEADER
# Recent Claude Coder Activity

> Auto-generated by sync-claude-activity.sh every 15 min. Last sync: $TIMESTAMP
> Codex: skip tasks listed here to avoid duplicate work.

## Completed Tasks (last 24h)

HEADER

if [ -n "$COMPLETED" ]; then
    echo "$COMPLETED" | while IFS= read -r line; do
        # Extract task description and repo
        if echo "$line" | grep -q "Task COMPLETED"; then
            TASK=$(echo "$line" | sed 's/.*Task COMPLETED: //' | sed 's/ ([0-9]* commits.*//')
            TS=$(echo "$line" | grep -oE '^\[[0-9-]+ [0-9:]+\]')
            echo "- $TS DONE: $TASK" >> "$DIGEST_FILE"
        elif echo "$line" | grep -q "Task FAILED"; then
            TASK=$(echo "$line" | sed 's/.*Task FAILED: //')
            TS=$(echo "$line" | grep -oE '^\[[0-9-]+ [0-9:]+\]')
            echo "- $TS FAILED: $TASK" >> "$DIGEST_FILE"
        elif echo "$line" | grep -q "Skipping already-completed"; then
            TASK=$(echo "$line" | sed 's/.*Skipping already-completed: //')
            echo "- SKIPPED (already done): $TASK" >> "$DIGEST_FILE"
        fi
    done
else
    echo "(no activity in last 24h)" >> "$DIGEST_FILE"
fi

cat >> "$DIGEST_FILE" << 'MIDHEADER'

## Active Claude Branches (unmerged)

| Repo | Branch | Last Commit | Subject |
|------|--------|-------------|---------|
MIDHEADER

if [ -n "$CLAUDE_BRANCHES" ]; then
    echo "$CLAUDE_BRANCHES" | while IFS='|' read -r repo branch datesubj; do
        CDATE=$(echo "$datesubj" | cut -d'|' -f1)
        SUBJ=$(echo "$datesubj" | cut -d'|' -f2-)
        echo "| $repo | \`$branch\` | $CDATE | $SUBJ |" >> "$DIGEST_FILE"
    done
else
    echo "| (none) | | | |" >> "$DIGEST_FILE"
fi

cat >> "$DIGEST_FILE" << 'FOOTER'

## What This Means for Codex

- Tasks marked DONE above are **already implemented** on `claude/*` branches — do not redo
- Tasks marked FAILED may need a different approach — check the branch for partial work
- If your automation touches the same area as an active branch, prefer building on it
FOOTER

# 4. Update TODO.md — mark completed items
if [ -f "$TODO_FILE" ] && [ -n "$COMPLETED" ]; then
    CHANGED=0
    echo "$COMPLETED" | grep "Task COMPLETED" | while IFS= read -r line; do
        # Extract key phrase from the task (first 40 chars for fuzzy matching)
        TASK=$(echo "$line" | sed 's/.*Task COMPLETED: //' | sed 's/ ([0-9]* commits.*//')
        # Try to find matching unchecked item in TODO.md
        MATCH_PHRASE=$(echo "$TASK" | cut -c1-50)
        if grep -qF "- [ ]" "$TODO_FILE" 2>/dev/null; then
            # Use python for safer in-place editing with fuzzy match
            python3 -c "
import sys, re
phrase = '''$MATCH_PHRASE'''.strip()[:50]
if not phrase:
    sys.exit(0)
words = phrase.lower().split()[:6]
with open('$TODO_FILE', 'r') as f:
    lines = f.readlines()
changed = False
for i, line in enumerate(lines):
    if '- [ ]' in line:
        lower = line.lower()
        matches = sum(1 for w in words if w in lower)
        if matches >= len(words) * 0.6:
            lines[i] = line.replace('- [ ]', '- [x]', 1).rstrip() + ' (claude-coder)\n'
            changed = True
            break
if changed:
    with open('$TODO_FILE', 'w') as f:
        f.writelines(lines)
" 2>/dev/null || true
        fi
    done
fi

# 5. Fetch latest from Mini bare repo (git only, no merge)
cd "$AAPM_DIR"
git fetch mini main --quiet 2>/dev/null || true

COMPLETED_COUNT=$(echo "$COMPLETED" | grep -c "Task COMPLETED" 2>/dev/null || echo "0")
BRANCH_COUNT=$(echo "$CLAUDE_BRANCHES" | grep -c "claude/" 2>/dev/null || echo "0")
log "Synced: $COMPLETED_COUNT completed, $BRANCH_COUNT branches"
