"""
Admin routes for block assignment import/export.

Provides endpoints for:
- CSV/Excel import preview
- Import execution
- Quick template creation
- Export to CSV/Excel
"""

from typing import Annotated

from fastapi import APIRouter, Depends, File, Form, HTTPException, UploadFile
from fastapi.responses import StreamingResponse
from sqlalchemy.ext.asyncio import AsyncSession

from app.core.logging import get_logger
from app.core.security import get_admin_user
from app.db.session import get_async_db
from app.models.user import User
from app.schemas.block_assignment_import import (
    BlockAssignmentExportRequest,
    BlockAssignmentImportRequest,
    BlockAssignmentImportResult,
    BlockAssignmentPreviewResponse,
    BlockAssignmentUploadRequest,
    ExportFormat,
    ImportFormat,
    QuickTemplateCreateRequest,
    QuickTemplateCreateResponse,
)
from app.services.block_assignment_export_service import (
    get_block_assignment_export_service,
)
from app.services.block_assignment_import_service import (
    BlockAssignmentImportService,
    get_block_assignment_import_service,
)

router = APIRouter()
logger = get_logger(__name__)


@router.post(
    "/preview",
    response_model=BlockAssignmentPreviewResponse,
    summary="Preview block assignment import",
    description="""
    Upload CSV content or file and get a preview of what will be imported.

    The preview shows:
    - Match status for each row (matched, unknown rotation, unknown resident, duplicate)
    - Confidence scores for fuzzy matches
    - Unknown rotations that need templates created

    **PERSEC**: Resident names are anonymized in the response.
    """,
)
async def preview_block_assignment_import(
    db: Annotated[AsyncSession, Depends(get_async_db)],
    current_user: Annotated[User, Depends(get_admin_user)],
    csv_content: Annotated[str | None, Form(description="CSV content (paste)")] = None,
    file: Annotated[UploadFile | None, File(description="CSV file upload")] = None,
    academic_year: Annotated[
        int | None,
        Form(description="Academic year (auto-detected if not provided)"),
    ] = None,
) -> BlockAssignmentPreviewResponse:
    """Generate import preview from CSV content or file."""
    # Validate input
    if not csv_content and not file:
        raise HTTPException(
            status_code=400,
            detail="Either csv_content or file must be provided",
        )

    # Read file content if provided
    content = csv_content
    if file:
        try:
            raw_content = await file.read()
            content = raw_content.decode("utf-8")
        except UnicodeDecodeError:
            raise HTTPException(
                status_code=400,
                detail="File must be UTF-8 encoded",
            )

    if not content or not content.strip():
        raise HTTPException(
            status_code=400,
            detail="Content is empty",
        )

    # Create request
    request = BlockAssignmentUploadRequest(
        content=content,
        academic_year=academic_year,
        format=ImportFormat.CSV,
    )

    # Generate preview
    service = get_block_assignment_import_service(db)
    preview = await service.preview_import(request)

    logger.info(
        f"Import preview generated by user {current_user.id}: "
        f"{preview.total_rows} rows, {preview.matched_count} matched"
    )

    return preview


@router.post(
    "/import",
    response_model=BlockAssignmentImportResult,
    summary="Execute block assignment import",
    description="""
    Execute import based on a previous preview.

    Options:
    - skip_duplicates: Skip rows that already exist
    - update_duplicates: Update existing assignments instead of skipping
    - row_overrides: Per-row override of duplicate action

    **Atomic**: All changes are committed in a single transaction.
    """,
)
async def execute_block_assignment_import(
    request: BlockAssignmentImportRequest,
    db: Annotated[AsyncSession, Depends(get_async_db)],
    current_user: Annotated[User, Depends(get_admin_user)],
) -> BlockAssignmentImportResult:
    """Execute import from preview."""
    service = get_block_assignment_import_service(db)
    result = await service.execute_import(request)

    logger.info(
        f"Import executed by user {current_user.id}: "
        f"{result.imported_count} imported, {result.updated_count} updated, "
        f"{result.skipped_count} skipped, {result.failed_count} failed"
    )

    return result


@router.post(
    "/templates/quick-create",
    response_model=QuickTemplateCreateResponse,
    summary="Quick-create rotation template",
    description="""
    Create a new rotation template during import.

    Used when an unknown rotation abbreviation is encountered in the preview.
    Creates a minimal template that can be edited later.
    """,
)
async def quick_create_rotation_template(
    request: QuickTemplateCreateRequest,
    db: Annotated[AsyncSession, Depends(get_async_db)],
    current_user: Annotated[User, Depends(get_admin_user)],
) -> QuickTemplateCreateResponse:
    """Create rotation template during import."""
    service = get_block_assignment_import_service(db)

    template = await service.create_quick_template(
        abbreviation=request.abbreviation,
        name=request.name,
        activity_type=request.activity_type,
        leave_eligible=request.leave_eligible,
    )

    logger.info(
        f"Quick template created by user {current_user.id}: "
        f"{template.abbreviation} - {template.name}"
    )

    return QuickTemplateCreateResponse(
        id=template.id,
        abbreviation=template.abbreviation,
        name=template.name,
        activity_type=template.activity_type,
    )


@router.get(
    "/template",
    summary="Download import template",
    description="Download a sample CSV template for block assignment import.",
)
async def download_import_template(
    current_user: Annotated[User, Depends(get_admin_user)],
) -> StreamingResponse:
    """Download CSV template."""
    template_content = """block_number,rotation_abbrev,resident_name
1,HILO,Smith
1,FMC,Jones
1,FMIT,Williams
2,CARDIO,Brown
2,EM,Davis
"""

    def generate():
        yield template_content

    return StreamingResponse(
        generate(),
        media_type="text/csv",
        headers={
            "Content-Disposition": "attachment; filename=block_assignments_template.csv"
        },
    )


@router.post(
    "/export",
    summary="Export block assignments",
    description="""
    Export block assignments to CSV or Excel format.

    **Filters:**
    - academic_year: Required year to export
    - block_numbers: Optional list of specific blocks
    - rotation_ids: Optional list of rotation IDs
    - resident_ids: Optional list of resident IDs

    **Options:**
    - format: csv or xlsx
    - include_pgy_level: Include PGY column
    - include_leave_status: Include leave columns
    - group_by: Optional grouping (block, resident, rotation)

    **Admin-only**: Full names are included (no PERSEC anonymization).
    """,
)
async def export_block_assignments(
    request: BlockAssignmentExportRequest,
    db: Annotated[AsyncSession, Depends(get_async_db)],
    current_user: Annotated[User, Depends(get_admin_user)],
) -> StreamingResponse:
    """Export block assignments to file."""
    service = get_block_assignment_export_service(db)
    file_bytes, filename, content_type = await service.export(request)

    logger.info(
        f"Export generated by user {current_user.id}: "
        f"year={request.academic_year}, format={request.format.value}, "
        f"filename={filename}"
    )

    def generate():
        yield file_bytes

    return StreamingResponse(
        generate(),
        media_type=content_type,
        headers={"Content-Disposition": f"attachment; filename={filename}"},
    )
