"""
Overnight Call Generation Constraint.

This module generates overnight call assignments for Sunday through Thursday.
Friday/Saturday are handled by FMIT mandatory call constraint.

Coverage Schedule:
    - Friday night: FMIT attending (see fmit.py)
    - Saturday night: FMIT attending (see fmit.py)
    - Sunday-Thursday: Generated by this constraint

Exclusions:
    - ADJUNCT faculty (not auto-scheduled)
    - Faculty on FMIT during their FMIT week
    - Faculty in post-FMIT Sunday blocking period
    - Faculty with blocking absences

Classes:
    - OvernightCallGenerationConstraint: Creates call variables and coverage constraints
    - NoConsecutiveCallConstraint: Soft constraint penalizing back-to-back call nights
    - FMITCallProximityConstraint: Distance-based exponential decay penalty near FMIT weeks
    - FriSatCallWeekExclusionConstraint: Alias for FMITCallProximityConstraint (backward compat)
"""

import logging
from collections import defaultdict
from datetime import date, timedelta
from typing import Any
from uuid import UUID

from app.models.person import FacultyRole

from .base import (
    ConstraintPriority,
    ConstraintResult,
    ConstraintType,
    ConstraintViolation,
    HardConstraint,
    SchedulingContext,
    SoftConstraint,
)
from .fmit import _identify_fmit_weeks_from_context, get_fmit_week_dates

logger = logging.getLogger(__name__)


def is_overnight_call_night(block_date: date) -> bool:
    """
    Check if date requires overnight call assignment.

    Args:
        block_date: Date to check

    Returns:
        True for Sunday-Thursday (weekday 6, 0, 1, 2, 3)
    """
    return block_date.weekday() in (6, 0, 1, 2, 3)  # Sun=6, Mon-Thu=0-3


class OvernightCallGenerationConstraint(SoftConstraint):  # @archetype-ok
    """
    Generates overnight call assignments for Sunday through Thursday nights.

    This is a HARD constraint that ensures exactly one faculty member is
    assigned to overnight call for each eligible night.

    Spacing guard: NoConsecutiveCallConstraint (registered in manager.py)

    Solver Variables Created:
        call_assignments[(f_i, b_i, "overnight")] = BoolVar

    Hard Rules:
        1. Exactly one faculty assigned per night (Sun-Thurs)
        2. ADJUNCT faculty excluded
        3. FMIT faculty blocked during their FMIT week
        4. Post-FMIT Sunday blocking respected
        5. Absence blocking respected
    """

    def __init__(self) -> None:
        """Initialize overnight call generation constraint."""
        super().__init__(
            name="OvernightCallGeneration",
            constraint_type=ConstraintType.CALL,
            weight=500,
            priority=ConstraintPriority.HIGH,
        )

    def _get_eligible_faculty(
        self,
        context: SchedulingContext,
        target_date: date,
        fmit_weeks_by_faculty: dict[UUID, list[tuple[date, date]]],
    ) -> list[tuple[Any, int]]:
        """
        Get faculty eligible for overnight call on a specific date.

        Args:
            context: Scheduling context
            target_date: Date to check eligibility for
            fmit_weeks_by_faculty: Pre-computed FMIT weeks by faculty ID

        Returns:
            List of (faculty, faculty_index) tuples
        """
        eligible = []

        call_eligible = context.call_eligible_faculty or context.faculty
        call_idx = context.call_eligible_faculty_idx or {
            fac.id: i for i, fac in enumerate(call_eligible)
        }

        for faculty in call_eligible:
            # Rule 1: Exclude ADJUNCT faculty
            if (
                hasattr(faculty, "role_enum")
                and faculty.role_enum == FacultyRole.ADJUNCT
            ):
                continue
            if hasattr(faculty, "faculty_role") and faculty.faculty_role == "adjunct":
                continue

            f_i = call_idx.get(faculty.id)
            if f_i is None:
                continue

            # Rule 2: Check FMIT blocking
            is_blocked = False
            if faculty.id in fmit_weeks_by_faculty:
                for friday_start, thursday_end in fmit_weeks_by_faculty[faculty.id]:
                    if friday_start <= target_date <= thursday_end:
                        is_blocked = True
                        break

            if is_blocked:
                continue

            # Rule 3: Check post-FMIT Sunday blocking
            if target_date.weekday() == 6:  # Sunday
                if faculty.id in fmit_weeks_by_faculty:
                    for friday_start, thursday_end in fmit_weeks_by_faculty[faculty.id]:
                        blocked_sunday = thursday_end + timedelta(days=3)
                        if target_date == blocked_sunday:
                            is_blocked = True
                            break

            if is_blocked:
                continue

            # Rule 4: Check availability (absences)
            if faculty.id in context.availability:
                for block in context.blocks:
                    if block.date == target_date:
                        block_avail = context.availability[faculty.id].get(block.id, {})
                        if not block_avail.get("available", True):
                            is_blocked = True
                            break

            if is_blocked:
                continue

            eligible.append((faculty, f_i))

        return eligible

    def _identify_fmit_weeks(
        self, context: SchedulingContext
    ) -> dict[UUID, list[tuple[date, date]]]:
        """
        Identify FMIT weeks from existing assignments.

        Returns:
            dict: {faculty_id: [(friday_start, thursday_end), ...]}
        """
        fmit_weeks: dict[UUID, set[tuple[date, date]]] = defaultdict(set)

        for a in context.existing_assignments:
            template = None
            for t in context.templates:
                if t.id == a.rotation_template_id:
                    template = t
                    break

            if not template:
                continue

            is_fmit = (
                hasattr(template, "rotation_type")
                and template.rotation_type == "inpatient"
                and hasattr(template, "name")
                and "FMIT" in template.name.upper()
            )

            if not is_fmit:
                continue

            block = None
            for b in context.blocks:
                if b.id == a.block_id:
                    block = b
                    break

            if not block:
                continue

            friday_start, thursday_end = get_fmit_week_dates(block.date)
            fmit_weeks[a.person_id].add((friday_start, thursday_end))

        return {k: list(v) for k, v in fmit_weeks.items()}

    def add_to_cpsat(
        self,
        model: Any,
        variables: dict[str, Any],
        context: SchedulingContext,
    ) -> None:
        """
        Add per-night FMIT/absence blocking to existing solver call variables.

        The solver (solvers.py) creates call BoolVars for ALL call-eligible
        faculty on ALL Sun-Thu nights. This constraint blocks ineligible
        faculty (FMIT week, post-FMIT Sunday, absences) by forcing their
        existing call vars to 0.
        """
        call_vars = variables.get("call_assignments", {})
        if not call_vars:
            return  # No solver-created variables to constrain

        fmit_weeks = self._identify_fmit_weeks(context)

        call_eligible = context.call_eligible_faculty or context.faculty
        if not call_eligible:
            return

        # Get unique dates from blocks
        dates_processed = set()
        blocked_count = 0

        for block in context.blocks:
            if block.date in dates_processed:
                continue
            if not is_overnight_call_night(block.date):
                continue
            dates_processed.add(block.date)

            target_date = block.date

            # Get eligible faculty for this night
            eligible = self._get_eligible_faculty(context, target_date, fmit_weeks)
            eligible_f_is = {f_i for _, f_i in eligible}

            # Find the b_i used by the solver for this date
            b_i = None
            for b in context.blocks:
                if b.date == target_date:
                    b_i = context.block_idx.get(b.id)
                    break
            if b_i is None:
                continue

            # Force ineligible faculty's call vars to 0 for this night
            for f_i in range(len(call_eligible)):
                key = (f_i, b_i, "overnight")
                if f_i not in eligible_f_is and key in call_vars:
                    model.Add(call_vars[key] == 0)
                    blocked_count += 1

        if blocked_count:
            logger.info(f"Blocked {blocked_count} ineligible call slots (FMIT/absence)")

    def add_to_pulp(
        self,
        model: Any,
        variables: dict[str, Any],
        context: SchedulingContext,
    ) -> None:
        """Add per-night FMIT/absence blocking to existing PuLP call variables."""
        call_vars = variables.get("call_assignments", {})
        if not call_vars:
            return

        fmit_weeks = self._identify_fmit_weeks(context)
        call_eligible = context.call_eligible_faculty or context.faculty
        if not call_eligible:
            return

        dates_processed = set()
        blocked_count = 0

        for block in context.blocks:
            if block.date in dates_processed:
                continue
            if not is_overnight_call_night(block.date):
                continue
            dates_processed.add(block.date)

            target_date = block.date
            eligible = self._get_eligible_faculty(context, target_date, fmit_weeks)
            eligible_f_is = {f_i for _, f_i in eligible}

            b_i = None
            for b in context.blocks:
                if b.date == target_date:
                    b_i = context.block_idx.get(b.id)
                    break
            if b_i is None:
                continue

            for f_i in range(len(call_eligible)):
                key = (f_i, b_i, "overnight")
                if f_i not in eligible_f_is and key in call_vars:
                    model += (call_vars[key] == 0, f"block_call_{f_i}_{target_date}")
                    blocked_count += 1

        if blocked_count:
            logger.info(f"Blocked {blocked_count} ineligible call slots (FMIT/absence)")

    def validate(
        self,
        assignments: list[Any],
        context: SchedulingContext,
    ) -> ConstraintResult:
        """Validate overnight call assignments."""
        violations: list[ConstraintViolation] = []
        fmit_weeks = self._identify_fmit_weeks(context)

        # Get unique dates requiring call
        dates = sorted(set(b.date for b in context.blocks))
        call_nights = [d for d in dates if is_overnight_call_night(d)]

        # Build map of call assignments by date
        calls_by_date: dict[date, list[Any]] = defaultdict(list)
        faculty_by_id = {f.id: f for f in context.faculty}

        for a in assignments:
            if not hasattr(a, "call_type") or a.call_type != "overnight":
                continue
            if hasattr(a, "date"):
                calls_by_date[a.date].append(a)

        # Check each night has exactly one call
        for night in call_nights:
            calls = calls_by_date.get(night, [])

            if len(calls) == 0:
                violations.append(
                    ConstraintViolation(
                        constraint_name=self.name,
                        constraint_type=self.constraint_type,
                        severity="CRITICAL",
                        message=f"No overnight call assigned for {night}",
                        details={"date": str(night)},
                    )
                )
            elif len(calls) > 1:
                violations.append(
                    ConstraintViolation(
                        constraint_name=self.name,
                        constraint_type=self.constraint_type,
                        severity="HIGH",
                        message=f"Multiple overnight calls on {night}",
                        details={"date": str(night), "count": len(calls)},
                    )
                )
            else:
                # Validate the assigned faculty is eligible
                call = calls[0]
                faculty = faculty_by_id.get(call.person_id)

                if faculty:
                    # Check ADJUNCT exclusion
                    is_adjunct = False
                    if (
                        hasattr(faculty, "role_enum")
                        and faculty.role_enum == FacultyRole.ADJUNCT
                    ):
                        is_adjunct = True
                    if (
                        hasattr(faculty, "faculty_role")
                        and faculty.faculty_role == "adjunct"
                    ):
                        is_adjunct = True

                    if is_adjunct:
                        faculty_name = getattr(faculty, "name", "Faculty")
                        violations.append(
                            ConstraintViolation(
                                constraint_name=self.name,
                                constraint_type=self.constraint_type,
                                severity="CRITICAL",
                                message=f"ADJUNCT faculty {faculty_name} assigned overnight call on {night}",
                                person_id=faculty.id,
                                details={"date": str(night)},
                            )
                        )

        return ConstraintResult(
            satisfied=len(violations) == 0,
            violations=violations,
        )


class NoConsecutiveCallConstraint(SoftConstraint):
    """
    Penalizes back-to-back and closely spaced overnight call nights for the same faculty.

    FMIT Fri/Sat pairs are expected and NOT penalized (they're preloaded,
    not solver-generated). This targets solver-generated Sun-Thu calls
    where the same faculty is assigned call within a few days.

    Applies an exponential decay penalty based on distance:
    - 1 day (consecutive): weight (default 100.0)
    - 2 days: weight / 2
    - 3 days: weight / 4
    - 4 days: 0 (no penalty)
    """

    def __init__(self, weight: float = 100.0) -> None:
        super().__init__(
            name="NoConsecutiveCall",
            constraint_type=ConstraintType.CALL,
            weight=weight,
            priority=ConstraintPriority.HIGH,
        )
        self.decay_weights = {
            1: self.weight,
            2: self.weight / 2.0,
            3: self.weight / 4.0,
        }

    def add_to_cpsat(
        self,
        model: Any,
        variables: dict[str, Any],
        context: SchedulingContext,
    ) -> None:
        """Add consecutive-call penalty to CP-SAT objective."""
        call_vars = variables.get("call_assignments", {})
        if not call_vars:
            return

        call_eligible = context.call_eligible_faculty or context.faculty
        if not call_eligible:
            return

        # Get sorted unique Sun-Thu dates from blocks
        call_dates = sorted(
            set(b.date for b in context.blocks if is_overnight_call_night(b.date))
        )
        if len(call_dates) < 2:
            return

        # Build date-to-block_idx map
        date_to_b_i: dict[date, int] = {}
        for b in context.blocks:
            if b.date not in date_to_b_i and is_overnight_call_night(b.date):
                b_i = context.block_idx.get(b.id)
                if b_i is not None:
                    date_to_b_i[b.date] = b_i

        objective_terms = variables.get("objective_terms", [])
        pair_count = 0

        call_idx = context.call_eligible_faculty_idx or {
            fac.id: i for i, fac in enumerate(call_eligible)
        }

        for faculty in call_eligible:
            f_i = call_idx.get(faculty.id)
            if f_i is None:
                continue

            # Check each pair of call nights
            for i in range(len(call_dates)):
                for j in range(i + 1, len(call_dates)):
                    d1, d2 = call_dates[i], call_dates[j]
                    gap = (d2 - d1).days

                    if gap > 3:
                        break  # Dates are sorted, gap will only increase

                    # Skip preloaded Friday/Saturday sequences (if they exist in this list)
                    if gap == 1 and d1.weekday() == 4:
                        continue

                    b_i1 = date_to_b_i.get(d1)
                    b_i2 = date_to_b_i.get(d2)
                    if b_i1 is None or b_i2 is None:
                        continue

                    key1 = (f_i, b_i1, "overnight")
                    key2 = (f_i, b_i2, "overnight")
                    if key1 not in call_vars or key2 not in call_vars:
                        continue

                    penalty_weight = int(self.decay_weights[gap])

                    # Create indicator: both_on = 1 iff both call vars are 1
                    both_on = model.NewBoolVar(f"consec_call_{f_i}_{d1}_{d2}")
                    model.AddBoolAnd([call_vars[key1], call_vars[key2]]).OnlyEnforceIf(
                        both_on
                    )
                    model.AddBoolOr(
                        [call_vars[key1].Not(), call_vars[key2].Not()]
                    ).OnlyEnforceIf(both_on.Not())

                    objective_terms.append((both_on, penalty_weight))
                    pair_count += 1

        variables["objective_terms"] = objective_terms
        logger.info(
            f"Added {pair_count} consecutive-call exponential penalty terms (max_weight={self.weight})"
        )

    def add_to_pulp(
        self,
        model: Any,
        variables: dict[str, Any],
        context: SchedulingContext,
    ) -> None:
        """Add consecutive-call penalty to PuLP objective."""
        import pulp

        call_vars = variables.get("call_assignments", {})
        if not call_vars:
            return

        call_eligible = context.call_eligible_faculty or context.faculty
        if not call_eligible:
            return

        call_dates = sorted(
            set(b.date for b in context.blocks if is_overnight_call_night(b.date))
        )
        if len(call_dates) < 2:
            return

        date_to_b_i: dict[date, int] = {}
        for b in context.blocks:
            if b.date not in date_to_b_i and is_overnight_call_night(b.date):
                b_i = context.block_idx.get(b.id)
                if b_i is not None:
                    date_to_b_i[b.date] = b_i

        call_idx = context.call_eligible_faculty_idx or {
            fac.id: i for i, fac in enumerate(call_eligible)
        }

        pair_count = 0
        for faculty in call_eligible:
            f_i = call_idx.get(faculty.id)
            if f_i is None:
                continue

            for i in range(len(call_dates)):
                for j in range(i + 1, len(call_dates)):
                    d1, d2 = call_dates[i], call_dates[j]
                    gap = (d2 - d1).days

                    if gap > 3:
                        break

                    if gap == 1 and d1.weekday() == 4:
                        continue

                    b_i1 = date_to_b_i.get(d1)
                    b_i2 = date_to_b_i.get(d2)
                    if b_i1 is None or b_i2 is None:
                        continue

                    key1 = (f_i, b_i1, "overnight")
                    key2 = (f_i, b_i2, "overnight")
                    if key1 not in call_vars or key2 not in call_vars:
                        continue

                    penalty_weight = self.decay_weights[gap]

                    # both = min(var1, var2) via auxiliary variable
                    both = pulp.LpVariable(f"consec_{f_i}_{d1}_{d2}", cat="Binary")
                    model += both <= call_vars[key1]
                    model += both <= call_vars[key2]
                    model += both >= call_vars[key1] + call_vars[key2] - 1

                    if "objective" in variables:
                        variables["objective"] += penalty_weight * both
                    pair_count += 1

        logger.info(
            f"Added {pair_count} consecutive-call exponential penalty terms (max_weight={self.weight})"
        )

    def validate(
        self,
        assignments: list[Any],
        context: SchedulingContext,
    ) -> ConstraintResult:
        """Validate no consecutive call assignments exist."""
        violations: list[ConstraintViolation] = []

        # Build call assignments by person and date
        calls_by_person: dict[UUID, list[date]] = defaultdict(list)
        for a in assignments:
            if hasattr(a, "call_type") and a.call_type == "overnight":
                if hasattr(a, "date"):
                    calls_by_person[a.person_id].append(a.date)

        penalty = 0.0
        for person_id, dates in calls_by_person.items():
            sorted_dates = sorted(dates)
            for i in range(len(sorted_dates)):
                for j in range(i + 1, len(sorted_dates)):
                    gap = (sorted_dates[j] - sorted_dates[i]).days

                    if gap > 3:
                        break

                    # Skip FMIT Fri+Sat pairs — expected preloaded pattern
                    if gap == 1 and sorted_dates[i].weekday() == 4:  # Friday
                        continue

                    penalty_weight = self.decay_weights.get(gap, 0.0)

                    violations.append(
                        ConstraintViolation(
                            constraint_name=self.name,
                            constraint_type=self.constraint_type,
                            severity="MEDIUM" if gap == 1 else "LOW",
                            message=(
                                f"Call spacing ({gap} days): {sorted_dates[i]} and "
                                f"{sorted_dates[j]}"
                            ),
                            person_id=person_id,
                            details={
                                "date1": str(sorted_dates[i]),
                                "date2": str(sorted_dates[j]),
                                "gap_days": gap,
                            },
                        )
                    )
                    penalty += penalty_weight

        return ConstraintResult(
            satisfied=True,  # Soft constraint
            violations=violations,
            penalty=penalty,
        )


class FMITCallProximityConstraint(SoftConstraint):
    """
    Distance-based exponential decay penalty for call near FMIT weeks.

    FMIT is a grueling 7-day inpatient week with mandatory Fri+Sat call.
    Having additional call anywhere near it is extremely undesirable.

    For each FMIT week (friday_start, thursday_end), penalizes call nights
    within `radius_days` of either boundary using exponential decay:

        penalty = base_weight / 2^((gap - 1) / half_life_days)

    where `gap` = days from call date to nearest FMIT boundary.

    | Gap | Penalty (base=10000, half_life=1) | vs Coverage (1000) |
    |-----|-----------------------------------|--------------------|
    | 1   | 10,000                            | 10× stronger       |
    | 2   | 5,000                             | 5× stronger        |
    | 3   | 2,500                             | 2.5× stronger      |
    | 4   | 1,250                             | 1.25× stronger     |
    | 5   | 625                               | Still beats most   |
    | 6   | 312                               | Moderate           |
    | 7   | 156                               | Mild               |

    Block-independent: Uses `_identify_fmit_weeks_from_context()` which
    handles cross-block FMIT visibility via eagerly loaded assignment.block.
    """

    def __init__(
        self,
        base_weight: float = 10_000.0,
        radius_days: int = 7,
        half_life_days: float = 1.0,
    ) -> None:
        super().__init__(
            name="FMITCallProximity",
            constraint_type=ConstraintType.CALL,
            priority=ConstraintPriority.HIGH,
            weight=base_weight,
        )
        self.base_weight = base_weight
        self.radius_days = radius_days
        self.half_life_days = half_life_days

    def _compute_penalty(self, gap: int) -> float:
        """Compute penalty for a given gap in days from FMIT boundary."""
        if gap < 1:
            return 0.0
        return self.base_weight / (2.0 ** ((gap - 1) / self.half_life_days))

    def _get_proximity_dates(
        self,
        fmit_weeks: dict[Any, list[tuple[date, date]]],
        faculty_id: Any,
    ) -> dict[date, float]:
        """
        Build {call_date: max_penalty} for all dates in proximity zones.

        If a date is near multiple FMIT weeks, uses the highest penalty.
        """
        date_penalties: dict[date, float] = {}

        weeks = fmit_weeks.get(faculty_id, [])
        for friday_start, thursday_end in weeks:
            # Before FMIT: friday_start - radius_days .. friday_start - 1
            for offset in range(1, self.radius_days + 1):
                d = friday_start - timedelta(days=offset)
                gap = offset
                penalty = self._compute_penalty(gap)
                if d in date_penalties:
                    date_penalties[d] = max(date_penalties[d], penalty)
                else:
                    date_penalties[d] = penalty

            # After FMIT: thursday_end + 1 .. thursday_end + radius_days
            for offset in range(1, self.radius_days + 1):
                d = thursday_end + timedelta(days=offset)
                gap = offset
                penalty = self._compute_penalty(gap)
                if d in date_penalties:
                    date_penalties[d] = max(date_penalties[d], penalty)
                else:
                    date_penalties[d] = penalty

        return date_penalties

    def add_to_cpsat(
        self,
        model: Any,
        variables: dict[str, Any],
        context: SchedulingContext,
    ) -> None:
        """Add proximity decay penalties to CP-SAT objective."""
        call_vars = variables.get("call_assignments", {})
        if not call_vars:
            return

        fmit_weeks = _identify_fmit_weeks_from_context(context)
        if not fmit_weeks:
            return

        # Build date→block_idx lookup for call nights
        call_date_to_b_i: dict[date, int] = {}
        for block in context.blocks:
            if (
                is_overnight_call_night(block.date)
                and block.date not in call_date_to_b_i
            ):
                b_i = context.block_idx.get(block.id)
                if b_i is not None:
                    call_date_to_b_i[block.date] = b_i

        call_idx = context.call_eligible_faculty_idx or {
            f.id: i
            for i, f in enumerate(context.call_eligible_faculty or context.faculty)
        }

        objective_terms = variables.get("objective_terms", [])
        term_count = 0

        for faculty_id, weeks in fmit_weeks.items():
            f_i = call_idx.get(faculty_id)
            if f_i is None:
                continue

            date_penalties = self._get_proximity_dates(fmit_weeks, faculty_id)

            for call_date, penalty in date_penalties.items():
                if not is_overnight_call_night(call_date):
                    continue
                b_i = call_date_to_b_i.get(call_date)
                if b_i is None:
                    continue
                key = (f_i, b_i, "overnight")
                if key in call_vars:
                    objective_terms.append((call_vars[key], int(penalty)))
                    term_count += 1

        variables["objective_terms"] = objective_terms
        if term_count:
            logger.info(
                f"Added {term_count} FMITCallProximity penalty terms "
                f"(base_weight={self.base_weight}, radius={self.radius_days}d)"
            )

    def add_to_pulp(
        self,
        model: Any,
        variables: dict[str, Any],
        context: SchedulingContext,
    ) -> None:
        """Add proximity decay penalties to PuLP objective."""
        call_vars = variables.get("call_assignments", {})
        if not call_vars:
            return

        fmit_weeks = _identify_fmit_weeks_from_context(context)
        if not fmit_weeks:
            return

        call_date_to_b_i: dict[date, int] = {}
        for block in context.blocks:
            if (
                is_overnight_call_night(block.date)
                and block.date not in call_date_to_b_i
            ):
                b_i = context.block_idx.get(block.id)
                if b_i is not None:
                    call_date_to_b_i[block.date] = b_i

        call_idx = context.call_eligible_faculty_idx or {
            f.id: i
            for i, f in enumerate(context.call_eligible_faculty or context.faculty)
        }

        term_count = 0

        for faculty_id, weeks in fmit_weeks.items():
            f_i = call_idx.get(faculty_id)
            if f_i is None:
                continue

            date_penalties = self._get_proximity_dates(fmit_weeks, faculty_id)

            for call_date, penalty in date_penalties.items():
                if not is_overnight_call_night(call_date):
                    continue
                b_i = call_date_to_b_i.get(call_date)
                if b_i is None:
                    continue
                key = (f_i, b_i, "overnight")
                if key in call_vars:
                    if "objective" in variables:
                        variables["objective"] += penalty * call_vars[key]
                    term_count += 1

        if term_count:
            logger.info(
                f"Added {term_count} FMITCallProximity penalty terms "
                f"(base_weight={self.base_weight}, radius={self.radius_days}d)"
            )

    def validate(
        self,
        assignments: list[Any],
        context: SchedulingContext,
    ) -> ConstraintResult:
        """Validate call proximity to FMIT weeks in finalized schedule."""
        violations: list[ConstraintViolation] = []

        fmit_weeks = _identify_fmit_weeks_from_context(context)
        if not fmit_weeks:
            return ConstraintResult(satisfied=True, violations=[], penalty=0.0)

        # Build call dates per person from assignments
        calls_by_person: dict[UUID, list[date]] = defaultdict(list)
        for a in assignments:
            if hasattr(a, "call_type") and a.call_type == "overnight":
                if hasattr(a, "date"):
                    calls_by_person[a.person_id].append(a.date)

        penalty = 0.0
        for person_id, weeks in fmit_weeks.items():
            call_dates = sorted(calls_by_person.get(person_id, []))
            if not call_dates:
                continue

            for call_date in call_dates:
                # Find minimum gap to any FMIT boundary
                min_gap = None
                for friday_start, thursday_end in weeks:
                    # Inside FMIT week — not our concern (hard-blocked)
                    if friday_start <= call_date <= thursday_end:
                        continue
                    if call_date < friday_start:
                        gap = (friday_start - call_date).days
                    else:
                        gap = (call_date - thursday_end).days
                    if min_gap is None or gap < min_gap:
                        min_gap = gap

                if min_gap is None or min_gap > self.radius_days:
                    continue

                call_penalty = self._compute_penalty(min_gap)
                penalty += call_penalty

                if min_gap <= 2:
                    severity = "HIGH"
                elif min_gap <= 4:
                    severity = "MEDIUM"
                else:
                    severity = "LOW"

                violations.append(
                    ConstraintViolation(
                        constraint_name=self.name,
                        constraint_type=self.constraint_type,
                        severity=severity,
                        message=(
                            f"Call on {call_date} is {min_gap} day(s) from FMIT boundary "
                            f"(penalty={call_penalty:.0f})"
                        ),
                        person_id=person_id,
                        details={
                            "call_date": str(call_date),
                            "gap_days": min_gap,
                            "penalty": call_penalty,
                        },
                    )
                )

        return ConstraintResult(
            satisfied=True,  # Soft constraint
            violations=violations,
            penalty=penalty,
        )


# Backward-compatible alias
FriSatCallWeekExclusionConstraint = FMITCallProximityConstraint
