"""
Overnight Call Generation Constraint.

This module generates overnight call assignments for Sunday through Thursday.
Friday/Saturday are handled by FMIT mandatory call constraint.

Coverage Schedule:
    - Friday night: FMIT attending (see fmit.py)
    - Saturday night: FMIT attending (see fmit.py)
    - Sunday-Thursday: Generated by this constraint

Exclusions:
    - ADJUNCT faculty (not auto-scheduled)
    - Faculty on FMIT during their FMIT week
    - Faculty in post-FMIT Sunday blocking period
    - Faculty with blocking absences

Classes:
    - OvernightCallGenerationConstraint: Creates call variables and coverage constraints
    - NoConsecutiveCallConstraint: Soft constraint penalizing back-to-back call nights
"""

import logging
from collections import defaultdict
from datetime import date, timedelta
from typing import Any
from uuid import UUID

from app.models.person import FacultyRole

from .base import (
    ConstraintPriority,
    ConstraintResult,
    ConstraintType,
    ConstraintViolation,
    HardConstraint,
    SchedulingContext,
    SoftConstraint,
)
from .fmit import get_fmit_week_dates

logger = logging.getLogger(__name__)


def is_overnight_call_night(block_date: date) -> bool:
    """
    Check if date requires overnight call assignment.

    Args:
        block_date: Date to check

    Returns:
        True for Sunday-Thursday (weekday 6, 0, 1, 2, 3)
    """
    return block_date.weekday() in (6, 0, 1, 2, 3)  # Sun=6, Mon-Thu=0-3


class OvernightCallGenerationConstraint(HardConstraint):  # @archetype-ok
    """
    Generates overnight call assignments for Sunday through Thursday nights.

    This is a HARD constraint that ensures exactly one faculty member is
    assigned to overnight call for each eligible night.

    Spacing guard: NoConsecutiveCallConstraint (registered in manager.py)

    Solver Variables Created:
        call_assignments[(f_i, b_i, "overnight")] = BoolVar

    Hard Rules:
        1. Exactly one faculty assigned per night (Sun-Thurs)
        2. ADJUNCT faculty excluded
        3. FMIT faculty blocked during their FMIT week
        4. Post-FMIT Sunday blocking respected
        5. Absence blocking respected
    """

    def __init__(self) -> None:
        """Initialize overnight call generation constraint."""
        super().__init__(
            name="OvernightCallGeneration",
            constraint_type=ConstraintType.CALL,
            priority=ConstraintPriority.HIGH,
        )

    def _get_eligible_faculty(
        self,
        context: SchedulingContext,
        target_date: date,
        fmit_weeks_by_faculty: dict[UUID, list[tuple[date, date]]],
    ) -> list[tuple[Any, int]]:
        """
        Get faculty eligible for overnight call on a specific date.

        Args:
            context: Scheduling context
            target_date: Date to check eligibility for
            fmit_weeks_by_faculty: Pre-computed FMIT weeks by faculty ID

        Returns:
            List of (faculty, faculty_index) tuples
        """
        eligible = []

        call_eligible = context.call_eligible_faculty or context.faculty
        call_idx = context.call_eligible_faculty_idx or {
            fac.id: i for i, fac in enumerate(call_eligible)
        }

        for faculty in call_eligible:
            # Rule 1: Exclude ADJUNCT faculty
            if (
                hasattr(faculty, "role_enum")
                and faculty.role_enum == FacultyRole.ADJUNCT
            ):
                continue
            if hasattr(faculty, "faculty_role") and faculty.faculty_role == "adjunct":
                continue

            f_i = call_idx.get(faculty.id)
            if f_i is None:
                continue

            # Rule 2: Check FMIT blocking
            is_blocked = False
            if faculty.id in fmit_weeks_by_faculty:
                for friday_start, thursday_end in fmit_weeks_by_faculty[faculty.id]:
                    if friday_start <= target_date <= thursday_end:
                        is_blocked = True
                        break

            if is_blocked:
                continue

            # Rule 3: Check post-FMIT Sunday blocking
            if target_date.weekday() == 6:  # Sunday
                if faculty.id in fmit_weeks_by_faculty:
                    for friday_start, thursday_end in fmit_weeks_by_faculty[faculty.id]:
                        blocked_sunday = thursday_end + timedelta(days=3)
                        if target_date == blocked_sunday:
                            is_blocked = True
                            break

            if is_blocked:
                continue

            # Rule 4: Check availability (absences)
            if faculty.id in context.availability:
                for block in context.blocks:
                    if block.date == target_date:
                        block_avail = context.availability[faculty.id].get(block.id, {})
                        if not block_avail.get("available", True):
                            is_blocked = True
                            break

            if is_blocked:
                continue

            eligible.append((faculty, f_i))

        return eligible

    def _identify_fmit_weeks(
        self, context: SchedulingContext
    ) -> dict[UUID, list[tuple[date, date]]]:
        """
        Identify FMIT weeks from existing assignments.

        Returns:
            dict: {faculty_id: [(friday_start, thursday_end), ...]}
        """
        fmit_weeks: dict[UUID, set[tuple[date, date]]] = defaultdict(set)

        for a in context.existing_assignments:
            template = None
            for t in context.templates:
                if t.id == a.rotation_template_id:
                    template = t
                    break

            if not template:
                continue

            is_fmit = (
                hasattr(template, "rotation_type")
                and template.rotation_type == "inpatient"
                and hasattr(template, "name")
                and "FMIT" in template.name.upper()
            )

            if not is_fmit:
                continue

            block = None
            for b in context.blocks:
                if b.id == a.block_id:
                    block = b
                    break

            if not block:
                continue

            friday_start, thursday_end = get_fmit_week_dates(block.date)
            fmit_weeks[a.person_id].add((friday_start, thursday_end))

        return {k: list(v) for k, v in fmit_weeks.items()}

    def add_to_cpsat(
        self,
        model: Any,
        variables: dict[str, Any],
        context: SchedulingContext,
    ) -> None:
        """
        Add per-night FMIT/absence blocking to existing solver call variables.

        The solver (solvers.py) creates call BoolVars for ALL call-eligible
        faculty on ALL Sun-Thu nights. This constraint blocks ineligible
        faculty (FMIT week, post-FMIT Sunday, absences) by forcing their
        existing call vars to 0.
        """
        call_vars = variables.get("call_assignments", {})
        if not call_vars:
            return  # No solver-created variables to constrain

        fmit_weeks = self._identify_fmit_weeks(context)

        call_eligible = context.call_eligible_faculty or context.faculty
        if not call_eligible:
            return

        # Get unique dates from blocks
        dates_processed = set()
        blocked_count = 0

        for block in context.blocks:
            if block.date in dates_processed:
                continue
            if not is_overnight_call_night(block.date):
                continue
            dates_processed.add(block.date)

            target_date = block.date

            # Get eligible faculty for this night
            eligible = self._get_eligible_faculty(context, target_date, fmit_weeks)
            eligible_f_is = {f_i for _, f_i in eligible}

            # Find the b_i used by the solver for this date
            b_i = None
            for b in context.blocks:
                if b.date == target_date:
                    b_i = context.block_idx.get(b.id)
                    break
            if b_i is None:
                continue

            # Force ineligible faculty's call vars to 0 for this night
            for f_i in range(len(call_eligible)):
                key = (f_i, b_i, "overnight")
                if f_i not in eligible_f_is and key in call_vars:
                    model.Add(call_vars[key] == 0)
                    blocked_count += 1

        if blocked_count:
            logger.info(f"Blocked {blocked_count} ineligible call slots (FMIT/absence)")

    def add_to_pulp(
        self,
        model: Any,
        variables: dict[str, Any],
        context: SchedulingContext,
    ) -> None:
        """Add per-night FMIT/absence blocking to existing PuLP call variables."""
        call_vars = variables.get("call_assignments", {})
        if not call_vars:
            return

        fmit_weeks = self._identify_fmit_weeks(context)
        call_eligible = context.call_eligible_faculty or context.faculty
        if not call_eligible:
            return

        dates_processed = set()
        blocked_count = 0

        for block in context.blocks:
            if block.date in dates_processed:
                continue
            if not is_overnight_call_night(block.date):
                continue
            dates_processed.add(block.date)

            target_date = block.date
            eligible = self._get_eligible_faculty(context, target_date, fmit_weeks)
            eligible_f_is = {f_i for _, f_i in eligible}

            b_i = None
            for b in context.blocks:
                if b.date == target_date:
                    b_i = context.block_idx.get(b.id)
                    break
            if b_i is None:
                continue

            for f_i in range(len(call_eligible)):
                key = (f_i, b_i, "overnight")
                if f_i not in eligible_f_is and key in call_vars:
                    model += (call_vars[key] == 0, f"block_call_{f_i}_{target_date}")
                    blocked_count += 1

        if blocked_count:
            logger.info(f"Blocked {blocked_count} ineligible call slots (FMIT/absence)")

    def validate(
        self,
        assignments: list[Any],
        context: SchedulingContext,
    ) -> ConstraintResult:
        """Validate overnight call assignments."""
        violations: list[ConstraintViolation] = []
        fmit_weeks = self._identify_fmit_weeks(context)

        # Get unique dates requiring call
        dates = sorted(set(b.date for b in context.blocks))
        call_nights = [d for d in dates if is_overnight_call_night(d)]

        # Build map of call assignments by date
        calls_by_date: dict[date, list[Any]] = defaultdict(list)
        faculty_by_id = {f.id: f for f in context.faculty}

        for a in assignments:
            if not hasattr(a, "call_type") or a.call_type != "overnight":
                continue
            if hasattr(a, "date"):
                calls_by_date[a.date].append(a)

        # Check each night has exactly one call
        for night in call_nights:
            calls = calls_by_date.get(night, [])

            if len(calls) == 0:
                violations.append(
                    ConstraintViolation(
                        constraint_name=self.name,
                        constraint_type=self.constraint_type,
                        severity="CRITICAL",
                        message=f"No overnight call assigned for {night}",
                        details={"date": str(night)},
                    )
                )
            elif len(calls) > 1:
                violations.append(
                    ConstraintViolation(
                        constraint_name=self.name,
                        constraint_type=self.constraint_type,
                        severity="HIGH",
                        message=f"Multiple overnight calls on {night}",
                        details={"date": str(night), "count": len(calls)},
                    )
                )
            else:
                # Validate the assigned faculty is eligible
                call = calls[0]
                faculty = faculty_by_id.get(call.person_id)

                if faculty:
                    # Check ADJUNCT exclusion
                    is_adjunct = False
                    if (
                        hasattr(faculty, "role_enum")
                        and faculty.role_enum == FacultyRole.ADJUNCT
                    ):
                        is_adjunct = True
                    if (
                        hasattr(faculty, "faculty_role")
                        and faculty.faculty_role == "adjunct"
                    ):
                        is_adjunct = True

                    if is_adjunct:
                        faculty_name = getattr(faculty, "name", "Faculty")
                        violations.append(
                            ConstraintViolation(
                                constraint_name=self.name,
                                constraint_type=self.constraint_type,
                                severity="CRITICAL",
                                message=f"ADJUNCT faculty {faculty_name} assigned overnight call on {night}",
                                person_id=faculty.id,
                                details={"date": str(night)},
                            )
                        )

        return ConstraintResult(
            satisfied=len(violations) == 0,
            violations=violations,
        )


class NoConsecutiveCallConstraint(SoftConstraint):
    """
    Penalizes back-to-back overnight call nights for the same faculty.

    FMIT Fri/Sat pairs are expected and NOT penalized (they're preloaded,
    not solver-generated). This only targets solver-generated Sun-Thu calls
    where the same faculty is assigned consecutive nights.

    The penalty is high (default 50.0) to strongly discourage back-to-back
    call, but as a soft constraint it won't make the model infeasible if
    8 faculty can't cleanly cover 5 nights/week.
    """

    def __init__(self, weight: float = 50.0) -> None:
        super().__init__(
            name="NoConsecutiveCall",
            constraint_type=ConstraintType.CALL,
            weight=weight,
            priority=ConstraintPriority.HIGH,
        )

    def add_to_cpsat(
        self,
        model: Any,
        variables: dict[str, Any],
        context: SchedulingContext,
    ) -> None:
        """Add consecutive-call penalty to CP-SAT objective."""
        call_vars = variables.get("call_assignments", {})
        if not call_vars:
            return

        call_eligible = context.call_eligible_faculty or context.faculty
        if not call_eligible:
            return

        # Get sorted unique Sun-Thu dates from blocks
        call_dates = sorted(
            set(b.date for b in context.blocks if is_overnight_call_night(b.date))
        )
        if len(call_dates) < 2:
            return

        # Build date-to-block_idx map
        date_to_b_i: dict[date, int] = {}
        for b in context.blocks:
            if b.date not in date_to_b_i and is_overnight_call_night(b.date):
                b_i = context.block_idx.get(b.id)
                if b_i is not None:
                    date_to_b_i[b.date] = b_i

        objective_terms = variables.get("objective_terms", [])
        pair_count = 0

        call_idx = context.call_eligible_faculty_idx or {
            fac.id: i for i, fac in enumerate(call_eligible)
        }

        for faculty in call_eligible:
            f_i = call_idx.get(faculty.id)
            if f_i is None:
                continue

            # Check each pair of consecutive call nights
            for i in range(len(call_dates) - 1):
                d1, d2 = call_dates[i], call_dates[i + 1]
                # Only penalize truly consecutive calendar days
                if (d2 - d1).days != 1:
                    continue

                b_i1 = date_to_b_i.get(d1)
                b_i2 = date_to_b_i.get(d2)
                if b_i1 is None or b_i2 is None:
                    continue

                key1 = (f_i, b_i1, "overnight")
                key2 = (f_i, b_i2, "overnight")
                if key1 not in call_vars or key2 not in call_vars:
                    continue

                # Create indicator: both_on = 1 iff both call vars are 1
                both_on = model.NewBoolVar(f"consec_call_{f_i}_{d1}_{d2}")
                model.AddBoolAnd([call_vars[key1], call_vars[key2]]).OnlyEnforceIf(
                    both_on
                )
                model.AddBoolOr(
                    [call_vars[key1].Not(), call_vars[key2].Not()]
                ).OnlyEnforceIf(both_on.Not())

                objective_terms.append((both_on, int(self.weight)))
                pair_count += 1

        variables["objective_terms"] = objective_terms
        logger.info(
            f"Added {pair_count} consecutive-call penalty terms (weight={self.weight})"
        )

    def add_to_pulp(
        self,
        model: Any,
        variables: dict[str, Any],
        context: SchedulingContext,
    ) -> None:
        """Add consecutive-call penalty to PuLP objective."""
        import pulp

        call_vars = variables.get("call_assignments", {})
        if not call_vars:
            return

        call_eligible = context.call_eligible_faculty or context.faculty
        if not call_eligible:
            return

        call_dates = sorted(
            set(b.date for b in context.blocks if is_overnight_call_night(b.date))
        )
        if len(call_dates) < 2:
            return

        date_to_b_i: dict[date, int] = {}
        for b in context.blocks:
            if b.date not in date_to_b_i and is_overnight_call_night(b.date):
                b_i = context.block_idx.get(b.id)
                if b_i is not None:
                    date_to_b_i[b.date] = b_i

        call_idx = context.call_eligible_faculty_idx or {
            fac.id: i for i, fac in enumerate(call_eligible)
        }

        pair_count = 0
        for faculty in call_eligible:
            f_i = call_idx.get(faculty.id)
            if f_i is None:
                continue

            for i in range(len(call_dates) - 1):
                d1, d2 = call_dates[i], call_dates[i + 1]
                if (d2 - d1).days != 1:
                    continue

                b_i1 = date_to_b_i.get(d1)
                b_i2 = date_to_b_i.get(d2)
                if b_i1 is None or b_i2 is None:
                    continue

                key1 = (f_i, b_i1, "overnight")
                key2 = (f_i, b_i2, "overnight")
                if key1 not in call_vars or key2 not in call_vars:
                    continue

                # both = min(var1, var2) via auxiliary variable
                both = pulp.LpVariable(f"consec_{f_i}_{d1}_{d2}", cat="Binary")
                model += both <= call_vars[key1]
                model += both <= call_vars[key2]
                model += both >= call_vars[key1] + call_vars[key2] - 1

                if "objective" in variables:
                    variables["objective"] += self.weight * both
                pair_count += 1

        logger.info(
            f"Added {pair_count} consecutive-call penalty terms (weight={self.weight})"
        )

    def validate(
        self,
        assignments: list[Any],
        context: SchedulingContext,
    ) -> ConstraintResult:
        """Validate no consecutive call assignments exist."""
        violations: list[ConstraintViolation] = []

        # Build call assignments by person and date
        calls_by_person: dict[UUID, list[date]] = defaultdict(list)
        for a in assignments:
            if hasattr(a, "call_type") and a.call_type == "overnight":
                if hasattr(a, "date"):
                    calls_by_person[a.person_id].append(a.date)

        penalty = 0.0
        for person_id, dates in calls_by_person.items():
            sorted_dates = sorted(dates)
            for i in range(len(sorted_dates) - 1):
                if (sorted_dates[i + 1] - sorted_dates[i]).days == 1:
                    violations.append(
                        ConstraintViolation(
                            constraint_name=self.name,
                            constraint_type=self.constraint_type,
                            severity="MEDIUM",
                            message=(
                                f"Back-to-back call: {sorted_dates[i]} and "
                                f"{sorted_dates[i + 1]}"
                            ),
                            person_id=person_id,
                            details={
                                "date1": str(sorted_dates[i]),
                                "date2": str(sorted_dates[i + 1]),
                            },
                        )
                    )
                    penalty += self.weight

        return ConstraintResult(
            satisfied=True,  # Soft constraint
            violations=violations,
            penalty=penalty,
        )
