"""SQLAlchemy model for RAG document storage with pgvector embeddings."""
from datetime import datetime
from typing import Optional
from uuid import UUID, uuid4

from sqlalchemy import DateTime, Index, String, Text, func
from sqlalchemy.dialects.postgresql import JSON, UUID as PGUUID
from sqlalchemy.orm import Mapped, mapped_column
from pgvector.sqlalchemy import Vector

from app.db.base import Base


class RAGDocument(Base):
    """Document chunks with vector embeddings for retrieval-augmented generation.

    Stores text chunks from various document sources (ACGME rules, scheduling docs,
    policies) with their embeddings for semantic search and context retrieval.

    Uses pgvector for efficient similarity search on 384-dimensional embeddings
    generated by sentence-transformers (all-MiniLM-L6-v2).
    """

    __tablename__ = "rag_documents"

    id: Mapped[UUID] = mapped_column(
        PGUUID(as_uuid=True), primary_key=True, default=uuid4
    )
    content: Mapped[str] = mapped_column(
        Text, nullable=False, comment="Text content of the document chunk"
    )
    embedding = mapped_column(
        Vector(384),
        nullable=False,
        comment="384-dimensional embedding from sentence-transformers",
    )
    doc_type: Mapped[str] = mapped_column(
        String(100),
        nullable=False,
        index=True,
        comment="Document type: acgme_rules, scheduling_policy, user_guide, etc.",
    )
    metadata_: Mapped[dict] = mapped_column(
        JSON,
        nullable=False,
        default=dict,
        comment="Additional metadata: source_file, page_number, section, etc.",
    )
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), nullable=False
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        server_default=func.now(),
        onupdate=func.now(),
        nullable=False,
    )

    # Create indexes for efficient retrieval
    __table_args__ = (
        # GIN index for metadata JSON queries
        Index("ix_rag_documents_metadata", "metadata_", postgresql_using="gin"),
        # HNSW index for vector similarity search (optimal for RAG queries)
        # m=16: connections per layer, ef_construction=64: search candidates during build
        Index(
            "ix_rag_documents_embedding_hnsw",
            "embedding",
            postgresql_using="hnsw",
            postgresql_with={"m": 16, "ef_construction": 64},
            postgresql_ops={"embedding": "vector_cosine_ops"},
        ),
        # IVFFlat index as alternative (faster build, slightly slower search)
        # lists=100: number of clusters for inverted file
        Index(
            "ix_rag_documents_embedding_ivfflat",
            "embedding",
            postgresql_using="ivfflat",
            postgresql_with={"lists": 100},
            postgresql_ops={"embedding": "vector_cosine_ops"},
        ),
    )

    def __repr__(self) -> str:
        """String representation."""
        return f"<RAGDocument(id={self.id}, doc_type={self.doc_type})>"
