"""Comprehensive monitoring and observability system.

This module provides:
- Metrics collection (request, database, scheduler, compliance metrics)
- Structured logging with data redaction and correlation IDs
- Alert management with routing and escalation
- Health checks for system dependencies
- OpenTelemetry distributed tracing
"""

# Metrics
from app.monitoring.metrics import (
    alert_manager,
    assignment_latency,
    burnout_reproduction_number,
    cache_eviction,
    cache_hit,
    cache_hit_rate,
    cache_miss,
    cache_size,
    cascade_failure_risk,
    compliance_check_count,
    compliance_rate,
    compliance_violation_count,
    concurrent_requests,
    db_connection_pool_size,
    db_connections_available,
    db_connections_in_use,
    db_query_count,
    db_query_latency,
    db_query_latency_summary,
    db_transaction_count,
    db_transaction_duration,
    defense_layer_status,
    error_count,
    error_rate,
    exception_count,
    max_work_hours,
    n_minus_one_contingency_count,
    n_minus_two_contingency_count,
    recovery_distance,
    recovery_time_objective,
    redis_connection_count,
    redis_memory_usage,
    resilience_health_score,
    resilience_level,
    rest_day_violation,
    schedule_generation_failure,
    schedule_generation_success,
    schedule_generation_time,
    schedule_quality_score,
    schedule_rotation_balance,
    solver_conflicts,
    solver_iterations,
    supervision_ratio_violation,
    swap_compatibility_check_time,
    swap_execution_count,
    swap_execution_time,
    swap_queue_depth,
    swap_request_count,
    swap_validation_failure,
    utilization_rate,
    work_hour_violation,
    active_users,
    api_key_usage,
    login_count,
    session_duration,
    user_action_count,
    user_role_distribution,
    get_all_metrics,
    record_cache_hit,
    record_cache_miss,
    record_compliance_check,
    record_database_query,
    record_error,
    record_request_metrics,
    record_schedule_generation,
    record_swap_execution,
    record_user_action,
    request_count,
    request_latency,
    request_latency_summary,
    request_size,
    response_size,
    update_active_users,
    update_cache_hit_rate,
    update_resilience_metrics,
    average_work_hours,
)

# Logging
from app.monitoring.logging_config import (
    AuditLogger,
    CorrelationIdFilter,
    JSONFormatter,
    LogLevelManager,
    PerformanceLogger,
    SecurityLogger,
    SensitiveDataRedactor,
    audit_logger,
    configure_logging,
    performance_logger,
    security_logger,
    setup_category_loggers,
    setup_rotating_handler,
    setup_timed_rotating_handler,
)

# Alerts
from app.monitoring.alerts import (
    Alert,
    AlertCategory,
    AlertDefinition,
    AlertManager,
    AlertSeverity,
    AlertStatus,
    EscalationPolicy,
    AlertRouter,
    CRITICAL_ALERTS,
    INFO_ALERTS,
    WARNING_ALERTS,
    alert_manager,
)

# Health Checks
from app.monitoring.health_checks import (
    HealthCheckCoordinator,
    HealthCheckResult,
    HealthStatus,
    DependencyType,
    OverallHealthResult,
    check_cpu_usage,
    check_database_health,
    check_disk_space,
    check_external_service,
    check_memory_usage,
    check_redis_health,
    health_check_coordinator,
)

# Tracing
from app.monitoring.tracing import (
    PerformanceTracer,
    TraceContext,
    TracingConfig,
    TracingSetup,
    create_span,
    get_tracer,
    performance_tracer,
    trace_context,
)

__all__ = [
    # Metrics exports
    'alert_manager',
    'assignment_latency',
    'burnout_reproduction_number',
    'cache_eviction',
    'cache_hit',
    'cache_hit_rate',
    'cache_miss',
    'cache_size',
    'cascade_failure_risk',
    'compliance_check_count',
    'compliance_rate',
    'compliance_violation_count',
    'concurrent_requests',
    'db_connection_pool_size',
    'db_connections_available',
    'db_connections_in_use',
    'db_query_count',
    'db_query_latency',
    'db_query_latency_summary',
    'db_transaction_count',
    'db_transaction_duration',
    'defense_layer_status',
    'error_count',
    'error_rate',
    'exception_count',
    'max_work_hours',
    'n_minus_one_contingency_count',
    'n_minus_two_contingency_count',
    'recovery_distance',
    'recovery_time_objective',
    'redis_connection_count',
    'redis_memory_usage',
    'resilience_health_score',
    'resilience_level',
    'rest_day_violation',
    'schedule_generation_failure',
    'schedule_generation_success',
    'schedule_generation_time',
    'schedule_quality_score',
    'schedule_rotation_balance',
    'solver_conflicts',
    'solver_iterations',
    'supervision_ratio_violation',
    'swap_compatibility_check_time',
    'swap_execution_count',
    'swap_execution_time',
    'swap_queue_depth',
    'swap_request_count',
    'swap_validation_failure',
    'utilization_rate',
    'work_hour_violation',
    'active_users',
    'api_key_usage',
    'login_count',
    'session_duration',
    'user_action_count',
    'user_role_distribution',
    'get_all_metrics',
    'record_cache_hit',
    'record_cache_miss',
    'record_compliance_check',
    'record_database_query',
    'record_error',
    'record_request_metrics',
    'record_schedule_generation',
    'record_swap_execution',
    'record_user_action',
    'request_count',
    'request_latency',
    'request_latency_summary',
    'request_size',
    'response_size',
    'update_active_users',
    'update_cache_hit_rate',
    'update_resilience_metrics',
    'average_work_hours',
    # Logging exports
    'AuditLogger',
    'CorrelationIdFilter',
    'JSONFormatter',
    'LogLevelManager',
    'PerformanceLogger',
    'SecurityLogger',
    'SensitiveDataRedactor',
    'audit_logger',
    'configure_logging',
    'performance_logger',
    'security_logger',
    'setup_category_loggers',
    'setup_rotating_handler',
    'setup_timed_rotating_handler',
    # Alerts exports
    'Alert',
    'AlertCategory',
    'AlertDefinition',
    'AlertManager',
    'AlertSeverity',
    'AlertStatus',
    'EscalationPolicy',
    'AlertRouter',
    'CRITICAL_ALERTS',
    'INFO_ALERTS',
    'WARNING_ALERTS',
    'alert_manager',
    # Health Checks exports
    'HealthCheckCoordinator',
    'HealthCheckResult',
    'HealthStatus',
    'DependencyType',
    'OverallHealthResult',
    'check_cpu_usage',
    'check_database_health',
    'check_disk_space',
    'check_external_service',
    'check_memory_usage',
    'check_redis_health',
    'health_check_coordinator',
    # Tracing exports
    'PerformanceTracer',
    'TraceContext',
    'TracingConfig',
    'TracingSetup',
    'create_span',
    'get_tracer',
    'performance_tracer',
    'trace_context',
]
