"""Add graduation_requirements table

Revision ID: 004773c4ac06
Revises: 3b9aea05c82e
Create Date: 2026-03-12 21:59:35.344445

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import app


# revision identifiers, used by Alembic.
revision: str = "004773c4ac06"
down_revision: str | None = "3b9aea05c82e"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "graduation_requirements",
        sa.Column("id", app.db.types.GUID(), nullable=False),
        sa.Column("pgy_level", sa.Integer(), nullable=False),
        sa.Column("rotation_template_id", app.db.types.GUID(), nullable=False),
        sa.Column("min_halves", sa.Integer(), nullable=False),
        sa.Column("target_halves", sa.Integer(), nullable=True),
        sa.Column("by_date", sa.Date(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["rotation_template_id"],
            ["rotation_templates.id"],
            name=op.f(
                "fk_graduation_requirements_rotation_template_id_rotation_templates"
            ),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_graduation_requirements")),
        sa.UniqueConstraint(
            "pgy_level", "rotation_template_id", name="uq_graduation_req_pgy_template"
        ),
    )
    op.create_index(
        op.f("ix_graduation_requirements_pgy_level"),
        "graduation_requirements",
        ["pgy_level"],
        unique=False,
    )
    op.create_index(
        op.f("ix_graduation_requirements_rotation_template_id"),
        "graduation_requirements",
        ["rotation_template_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_graduation_requirements_rotation_template_id"),
        table_name="graduation_requirements",
    )
    op.drop_index(
        op.f("ix_graduation_requirements_pgy_level"),
        table_name="graduation_requirements",
    )
    op.drop_table("graduation_requirements")
    # ### end Alembic commands ###
