"""Add game theory tables

Revision ID: a399bc3fb338
Revises: 20260219_ai_budget_tables
Create Date: 2026-02-19 13:48:30.664203

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import app.db.types

# revision identifiers, used by Alembic.
revision: str = "a399bc3fb338"
down_revision: str | None = "20260219_ai_budget_tables"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "game_theory_strategies",
        sa.Column("id", app.db.types.GUID(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("strategy_type", sa.String(length=30), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("created_by", sa.String(length=100), nullable=True),
        sa.Column("utilization_target", sa.Float(), nullable=True),
        sa.Column("cross_zone_borrowing", sa.Boolean(), nullable=True),
        sa.Column("sacrifice_willingness", sa.String(length=20), nullable=True),
        sa.Column("defense_activation_threshold", sa.Integer(), nullable=True),
        sa.Column("response_timeout_ms", sa.Integer(), nullable=True),
        sa.Column("initial_action", sa.String(length=10), nullable=True),
        sa.Column("forgiveness_probability", sa.Float(), nullable=True),
        sa.Column("retaliation_memory", sa.Integer(), nullable=True),
        sa.Column("is_stochastic", sa.Boolean(), nullable=True),
        sa.Column("custom_logic", app.db.types.JSONType(), nullable=True),
        sa.Column("tournaments_participated", sa.Integer(), nullable=True),
        sa.Column("total_matches", sa.Integer(), nullable=True),
        sa.Column("total_wins", sa.Integer(), nullable=True),
        sa.Column("average_score", sa.Float(), nullable=True),
        sa.Column("cooperation_rate", sa.Float(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_game_theory_strategies")),
    )

    op.create_table(
        "game_theory_tournaments",
        sa.Column("id", app.db.types.GUID(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("created_by", sa.String(length=100), nullable=True),
        sa.Column("turns_per_match", sa.Integer(), nullable=False),
        sa.Column("repetitions", sa.Integer(), nullable=False),
        sa.Column("noise", sa.Float(), nullable=True),
        sa.Column("payoff_cc", sa.Float(), nullable=True),
        sa.Column("payoff_cd", sa.Float(), nullable=True),
        sa.Column("payoff_dc", sa.Float(), nullable=True),
        sa.Column("payoff_dd", sa.Float(), nullable=True),
        sa.Column("strategy_ids", app.db.types.StringArrayType(), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("started_at", sa.DateTime(), nullable=True),
        sa.Column("completed_at", sa.DateTime(), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("celery_task_id", sa.String(length=100), nullable=True),
        sa.Column("total_matches", sa.Integer(), nullable=True),
        sa.Column("winner_strategy_id", app.db.types.GUID(), nullable=True),
        sa.Column("winner_strategy_name", sa.String(length=100), nullable=True),
        sa.Column("results_json", app.db.types.JSONType(), nullable=True),
        sa.Column("rankings", app.db.types.JSONType(), nullable=True),
        sa.Column("payoff_matrix", app.db.types.JSONType(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_game_theory_tournaments")),
    )

    op.create_table(
        "game_theory_evolution",
        sa.Column("id", app.db.types.GUID(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("created_by", sa.String(length=100), nullable=True),
        sa.Column("initial_population_size", sa.Integer(), nullable=False),
        sa.Column("turns_per_interaction", sa.Integer(), nullable=False),
        sa.Column("max_generations", sa.Integer(), nullable=True),
        sa.Column("mutation_rate", sa.Float(), nullable=True),
        sa.Column("initial_composition", app.db.types.JSONType(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("started_at", sa.DateTime(), nullable=True),
        sa.Column("completed_at", sa.DateTime(), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("celery_task_id", sa.String(length=100), nullable=True),
        sa.Column("generations_completed", sa.Integer(), nullable=True),
        sa.Column("winner_strategy_id", app.db.types.GUID(), nullable=True),
        sa.Column("winner_strategy_name", sa.String(length=100), nullable=True),
        sa.Column("is_evolutionarily_stable", sa.Boolean(), nullable=True),
        sa.Column("population_history", app.db.types.JSONType(), nullable=True),
        sa.Column("final_population", app.db.types.JSONType(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_game_theory_evolution")),
    )

    op.create_table(
        "game_theory_matches",
        sa.Column("id", app.db.types.GUID(), nullable=False),
        sa.Column("tournament_id", app.db.types.GUID(), nullable=False),
        sa.Column("strategy1_id", app.db.types.GUID(), nullable=False),
        sa.Column("strategy1_name", sa.String(length=100), nullable=True),
        sa.Column("strategy2_id", app.db.types.GUID(), nullable=False),
        sa.Column("strategy2_name", sa.String(length=100), nullable=True),
        sa.Column("score1", sa.Float(), nullable=False),
        sa.Column("score2", sa.Float(), nullable=False),
        sa.Column("cooperation_rate1", sa.Float(), nullable=True),
        sa.Column("cooperation_rate2", sa.Float(), nullable=True),
        sa.Column("actions1", sa.Text(), nullable=True),
        sa.Column("actions2", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["strategy1_id"],
            ["game_theory_strategies.id"],
            name=op.f("fk_game_theory_matches_strategy1_id_game_theory_strategies"),
        ),
        sa.ForeignKeyConstraint(
            ["strategy2_id"],
            ["game_theory_strategies.id"],
            name=op.f("fk_game_theory_matches_strategy2_id_game_theory_strategies"),
        ),
        sa.ForeignKeyConstraint(
            ["tournament_id"],
            ["game_theory_tournaments.id"],
            name=op.f("fk_game_theory_matches_tournament_id_game_theory_tournaments"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_game_theory_matches")),
    )

    op.create_table(
        "game_theory_validations",
        sa.Column("id", app.db.types.GUID(), nullable=False),
        sa.Column("strategy_id", app.db.types.GUID(), nullable=False),
        sa.Column("strategy_name", sa.String(length=100), nullable=True),
        sa.Column("validated_at", sa.DateTime(), nullable=False),
        sa.Column("turns", sa.Integer(), nullable=True),
        sa.Column("repetitions", sa.Integer(), nullable=True),
        sa.Column("passed", sa.Boolean(), nullable=False),
        sa.Column("average_score", sa.Float(), nullable=False),
        sa.Column("cooperation_rate", sa.Float(), nullable=False),
        sa.Column("pass_threshold", sa.Float(), nullable=True),
        sa.Column("assessment", sa.String(length=50), nullable=True),
        sa.Column("recommendation", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["strategy_id"],
            ["game_theory_strategies.id"],
            name=op.f("fk_game_theory_validations_strategy_id_game_theory_strategies"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_game_theory_validations")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("game_theory_validations")
    op.drop_table("game_theory_matches")
    op.drop_table("game_theory_evolution")
    op.drop_table("game_theory_tournaments")
    op.drop_table("game_theory_strategies")
    # ### end Alembic commands ###
