"""Pydantic schemas for API validation."""

from app.schemas.absence import AbsenceCreate, AbsenceResponse, AbsenceUpdate
from app.schemas.assignment import (
    AssignmentCreate,
    AssignmentResponse,
    AssignmentUpdate,
)
from app.schemas.auth import Token, TokenData, UserCreate, UserLogin, UserResponse
from app.schemas.block import BlockCreate, BlockListResponse, BlockResponse
from app.schemas.certification import (
    CertificationTypeCreate,
    CertificationTypeListResponse,
    CertificationTypeResponse,
    CertificationTypeUpdate,
    ComplianceSummaryResponse,
    ExpiringCertificationsListResponse,
    PersonCertificationCreate,
    PersonCertificationListResponse,
    PersonCertificationResponse,
    PersonCertificationUpdate,
    PersonCertificationWithTypeResponse,
    PersonComplianceResponse,
)
from app.schemas.email import (
    EmailLogCreate,
    EmailLogListResponse,
    EmailLogRead,
    EmailLogUpdate,
    EmailTemplateCreate,
    EmailTemplateListResponse,
    EmailTemplateRead,
    EmailTemplateSummary,
    EmailTemplateUpdate,
)
from app.schemas.leave import (
    BulkLeaveImportRequest,
    BulkLeaveImportResponse,
    LeaveCalendarEntry,
    LeaveCalendarResponse,
    LeaveCreateRequest,
    LeaveListResponse,
    LeaveResponse,
    LeaveType,
    LeaveUpdateRequest,
    LeaveWebhookPayload,
)
from app.schemas.person import (
    PersonCreate,
    PersonListResponse,
    PersonResponse,
    PersonUpdate,
)
from app.schemas.portal import (
    DashboardAlert,
    DashboardResponse,
    DashboardStats,
    FMITWeekInfo,
    MarketplaceEntry,
    MarketplaceResponse,
    MyScheduleResponse,
    MySwapsResponse,
    PreferencesResponse,
    PreferencesUpdate,
    SwapRequestCreate,
    SwapRequestResponse,
    SwapRequestStatus,
    SwapRequestSummary,
    SwapRespondRequest,
)
from app.schemas.rag import (
    ContextBuildRequest,
    DocumentChunk,
    DocumentIngestRequest,
    IngestResponse,
    RAGContext,
    RAGHealthResponse,
    RAGRetrievalRequest,
    RetrievalResponse,
    RetrievedDocument,
)
from app.schemas.procedure import (
    ProcedureCreate,
    ProcedureListResponse,
    ProcedureResponse,
    ProcedureSummary,
    ProcedureUpdate,
)
from app.schemas.procedure_credential import (
    CredentialCreate,
    CredentialListResponse,
    CredentialResponse,
    CredentialUpdate,
    CredentialWithProcedureListResponse,
    CredentialWithProcedureResponse,
    FacultyCredentialSummary,
    QualifiedFacultyResponse,
)
from app.schemas.rotation_template import (
    RotationTemplateCreate,
    RotationTemplateListResponse,
    RotationTemplateResponse,
    RotationTemplateUpdate,
)
from app.schemas.schedule import ScheduleRequest, ScheduleResponse, ValidationResult
from app.schemas.schedule_override import (
    ScheduleOverrideCreate,
    ScheduleOverrideListResponse,
    ScheduleOverrideResponse,
)
from app.schemas.settings import SettingsCreate, SettingsResponse, SettingsUpdate
from app.schemas.swap import (
    SwapApprovalRequest,
    SwapExecuteRequest,
    SwapExecuteResponse,
    SwapHistoryFilter,
    SwapHistoryResponse,
    SwapRecordResponse,
    SwapRollbackRequest,
    SwapStatusSchema,
    SwapTypeSchema,
    SwapValidationResult,
)
from app.schemas.swap_matching import (
    AutoMatchResult,
    BatchAutoMatchResult,
    MatchingAnalytics,
    MatchingCriteria,
    MatchingSuggestion,
    MatchPriority,
    MatchType,
    RankedMatch,
    ScoringBreakdown,
    SwapMatch,
)
from app.schemas.var_analytics import (
    ConditionalVaRRequest,
    ConditionalVaRResponse,
    CoverageVaRRequest,
    CoverageVaRResponse,
    RiskSeverity,
    VaRMetric,
    WorkloadVaRRequest,
    WorkloadVaRResponse,
)
from app.schemas.hopfield_schemas import (
    AttractorInfoResponse,
    AttractorType,
    BasinDepthRequest,
    BasinDepthResponse,
    BasinMetricsResponse,
    EnergyMetricsResponse,
    HopfieldEnergyRequest,
    HopfieldEnergyResponse,
    NearbyAttractorsRequest,
    NearbyAttractorsResponse,
    SpuriousAttractorInfoResponse,
    SpuriousAttractorsRequest,
    SpuriousAttractorsResponse,
    StabilityLevel,
)

__all__ = [
    "PersonCreate",
    "PersonUpdate",
    "PersonResponse",
    "PersonListResponse",
    "BlockCreate",
    "BlockResponse",
    "BlockListResponse",
    "RotationTemplateCreate",
    "RotationTemplateUpdate",
    "RotationTemplateResponse",
    "RotationTemplateListResponse",
    "AssignmentCreate",
    "AssignmentUpdate",
    "AssignmentResponse",
    "AbsenceCreate",
    "AbsenceUpdate",
    "AbsenceResponse",
    "ScheduleRequest",
    "ScheduleResponse",
    "ValidationResult",
    "ScheduleOverrideCreate",
    "ScheduleOverrideListResponse",
    "ScheduleOverrideResponse",
    "SettingsCreate",
    "SettingsUpdate",
    "SettingsResponse",
    "Token",
    "TokenData",
    "UserLogin",
    "UserCreate",
    "UserResponse",
    # Procedure credentialing
    "ProcedureCreate",
    "ProcedureUpdate",
    "ProcedureResponse",
    "ProcedureListResponse",
    "ProcedureSummary",
    "CredentialCreate",
    "CredentialUpdate",
    "CredentialResponse",
    "CredentialListResponse",
    "CredentialWithProcedureResponse",
    "CredentialWithProcedureListResponse",
    "QualifiedFacultyResponse",
    "FacultyCredentialSummary",
    # Certification tracking
    "CertificationTypeCreate",
    "CertificationTypeUpdate",
    "CertificationTypeResponse",
    "CertificationTypeListResponse",
    "PersonCertificationCreate",
    "PersonCertificationUpdate",
    "PersonCertificationResponse",
    "PersonCertificationListResponse",
    "PersonCertificationWithTypeResponse",
    "ExpiringCertificationsListResponse",
    "ComplianceSummaryResponse",
    "PersonComplianceResponse",
    # Email notification schemas
    "EmailLogCreate",
    "EmailLogUpdate",
    "EmailLogRead",
    "EmailLogListResponse",
    "EmailTemplateCreate",
    "EmailTemplateUpdate",
    "EmailTemplateRead",
    "EmailTemplateListResponse",
    "EmailTemplateSummary",
    # FMIT Swap schemas
    "SwapStatusSchema",
    "SwapTypeSchema",
    "SwapExecuteRequest",
    "SwapApprovalRequest",
    "SwapRollbackRequest",
    "SwapHistoryFilter",
    "SwapValidationResult",
    "SwapRecordResponse",
    "SwapExecuteResponse",
    "SwapHistoryResponse",
    # Leave schemas
    "LeaveType",
    "LeaveWebhookPayload",
    "LeaveCreateRequest",
    "LeaveUpdateRequest",
    "LeaveResponse",
    "LeaveListResponse",
    "LeaveCalendarEntry",
    "LeaveCalendarResponse",
    "BulkLeaveImportRequest",
    "BulkLeaveImportResponse",
    # Portal schemas
    "SwapRequestStatus",
    "FMITWeekInfo",
    "MyScheduleResponse",
    "SwapRequestSummary",
    "MySwapsResponse",
    "SwapRequestCreate",
    "SwapRequestResponse",
    "SwapRespondRequest",
    "PreferencesUpdate",
    "PreferencesResponse",
    "DashboardAlert",
    "DashboardStats",
    "DashboardResponse",
    "MarketplaceEntry",
    "MarketplaceResponse",
    # Swap matching schemas
    "MatchType",
    "MatchPriority",
    "SwapMatch",
    "ScoringBreakdown",
    "RankedMatch",
    "AutoMatchResult",
    "BatchAutoMatchResult",
    "MatchingCriteria",
    "MatchingSuggestion",
    "MatchingAnalytics",
    # RAG schemas
    "DocumentIngestRequest",
    "DocumentChunk",
    "RetrievedDocument",
    "IngestResponse",
    "RAGRetrievalRequest",
    "RetrievalResponse",
    "ContextBuildRequest",
    "RAGContext",
    "RAGHealthResponse",
    # VaR analytics schemas
    "RiskSeverity",
    "VaRMetric",
    "CoverageVaRRequest",
    "CoverageVaRResponse",
    "WorkloadVaRRequest",
    "WorkloadVaRResponse",
    "ConditionalVaRRequest",
    "ConditionalVaRResponse",
    # Hopfield network schemas
    "AttractorInfoResponse",
    "AttractorType",
    "BasinDepthRequest",
    "BasinDepthResponse",
    "BasinMetricsResponse",
    "EnergyMetricsResponse",
    "HopfieldEnergyRequest",
    "HopfieldEnergyResponse",
    "NearbyAttractorsRequest",
    "NearbyAttractorsResponse",
    "SpuriousAttractorInfoResponse",
    "SpuriousAttractorsRequest",
    "SpuriousAttractorsResponse",
    "StabilityLevel",
]
