"""Schema definitions for Claude Code chat integration."""

from typing import Any, Dict, List, Optional
from datetime import datetime
from pydantic import BaseModel, Field


class StreamUpdate(BaseModel):
    """Server-Sent Event (SSE) update from Claude streaming."""

    type: str = Field(
        ..., description="Update type: text, code, artifact, status, error"
    )
    content: str = Field(..., description="The update content")
    metadata: dict[str, Any] | None = Field(
        None, description="Additional metadata for the update"
    )


class CodeBlock(BaseModel):
    """Code block in message response."""

    language: str
    code: str
    filename: str | None = None


class ChatArtifact(BaseModel):
    """Artifact generated by Claude (schedule, report, etc)."""

    id: str
    type: str = Field(
        ...,
        description="Artifact type: schedule, analysis, report, configuration",
    )
    title: str
    data: dict[str, Any]
    created_at: datetime = Field(default_factory=datetime.utcnow)


class ChatMessage(BaseModel):
    """Chat message in session."""

    id: str
    role: str = Field(..., description="user, assistant, or system")
    content: str
    timestamp: datetime = Field(default_factory=datetime.utcnow)
    is_streaming: bool = False
    error: str | None = None
    code_blocks: list[CodeBlock] | None = None
    artifacts: list[ChatArtifact] | None = None


class ConstraintContext(BaseModel):
    """Scheduling constraints context."""

    max_hours_per_week: int = 80
    max_consecutive_days: int = 7
    min_rest_days: int = 1
    min_rotation_length: int = 4
    custom_rules: list[str] | None = None


class ResidentContext(BaseModel):
    """Individual resident context."""

    id: str
    name: str
    preferred_rotations: list[str] | None = None
    restrictions: list[str] | None = None
    absences: list[dict[str, Any]] | None = None


class RotationContext(BaseModel):
    """Rotation block context."""

    id: str
    name: str
    residents: list[str]
    start_date: datetime
    end_date: datetime


class ScheduleContext(BaseModel):
    """Schedule context for execution."""

    academic_year: str
    weeks: int
    rotations: list[RotationContext]


class ClaudeCodeExecutionContext(BaseModel):
    """Full execution context for Claude Code."""

    program_id: str
    admin_id: str
    session_id: str
    current_schedule: ScheduleContext | None = None
    constraints: ConstraintContext | None = None
    residents: list[ResidentContext] | None = None


class ClaudeCodeRequest(BaseModel):
    """Request to Claude Code agent."""

    action: str = Field(
        "custom",
        description="Task type: generate_schedule, analyze_violations, optimize_fairness, validate_compliance, export_report, custom",
    )
    context: ClaudeCodeExecutionContext
    parameters: dict[str, Any] | None = None
    user_query: str


class ClaudeCodeResponse(BaseModel):
    """Response from Claude Code agent."""

    success: bool
    message: str
    result: dict[str, Any] | None = None
    artifacts: list[ChatArtifact] | None = None
    next_actions: list[str] | None = None
    error: str | None = None


class ChatSession(BaseModel):
    """Chat session metadata."""

    id: str
    title: str
    messages: list[ChatMessage] = []
    created_at: datetime = Field(default_factory=datetime.utcnow)
    updated_at: datetime = Field(default_factory=datetime.utcnow)
    program_id: str
    admin_id: str


class ChatHistoryExport(BaseModel):
    """Exported chat history with all metadata."""

    session: ChatSession
    total_messages: int
    artifacts_generated: int
    duration_minutes: float
