#!/bin/bash
# generate-standing-orders-index.sh
# Generates STANDING_ORDERS_INDEX.md from identity cards
#
# Usage: ./scripts/generate-standing-orders-index.sh
#
# This script extracts standing orders from all .identity.md files
# and generates a consolidated index in .claude/Governance/

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(dirname "$SCRIPT_DIR")"
IDENTITIES_DIR="$PROJECT_ROOT/.claude/Identities"
OUTPUT_FILE="$PROJECT_ROOT/.claude/Governance/STANDING_ORDERS_INDEX.md"

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

echo -e "${GREEN}Generating Standing Orders Index...${NC}"

# Check identities directory exists
if [[ ! -d "$IDENTITIES_DIR" ]]; then
    echo -e "${RED}Error: Identities directory not found: $IDENTITIES_DIR${NC}"
    exit 1
fi

# Count identity files
IDENTITY_COUNT=$(find "$IDENTITIES_DIR" -name "*.identity.md" -not -name "TEMPLATE*" | wc -l | tr -d ' ')
echo -e "Found ${YELLOW}$IDENTITY_COUNT${NC} identity cards"

# Generate header
cat > "$OUTPUT_FILE" << 'HEADER'
# PAI Standing Orders Index

> **Generated:** $(date +%Y-%m-%d)
> **Source:** `.claude/Identities/*.identity.md`
> **Regenerate:** `./scripts/generate-standing-orders-index.sh`

---

## Overview

Standing Orders are pre-authorized actions that agents can execute without seeking approval from their supervisor. They represent the trusted, routine operations within each agent's domain.

**Doctrine:** Standing orders implement Auftragstaktik by encoding commander's intent at each level. Agents act autonomously within these boundaries.

---

## Index by Agent

HEADER

# Update the date in the header
sed -i '' "s/\$(date +%Y-%m-%d)/$(date +%Y-%m-%d)/" "$OUTPUT_FILE" 2>/dev/null || \
sed -i "s/\$(date +%Y-%m-%d)/$(date +%Y-%m-%d)/" "$OUTPUT_FILE"

# Process each identity file
for identity_file in "$IDENTITIES_DIR"/*.identity.md; do
    filename=$(basename "$identity_file")
    agent_name="${filename%.identity.md}"

    # Skip template file
    if [[ "$agent_name" == "TEMPLATE" ]]; then
        continue
    fi

    # Extract standing orders section
    standing_orders=$(awk '/^## Standing Orders/,/^## [A-Z]/' "$identity_file" | \
        grep -E '^[0-9]+\.' || true)

    if [[ -n "$standing_orders" ]]; then
        echo "### $agent_name" >> "$OUTPUT_FILE"
        echo "" >> "$OUTPUT_FILE"
        echo "$standing_orders" >> "$OUTPUT_FILE"
        echo "" >> "$OUTPUT_FILE"
        echo -e "  ${GREEN}+${NC} $agent_name"
    else
        echo -e "  ${YELLOW}-${NC} $agent_name (no standing orders)"
    fi
done

# Add footer
cat >> "$OUTPUT_FILE" << 'FOOTER'

---

## Usage

Standing orders should be consulted when:
1. An agent is uncertain whether an action requires approval
2. Reviewing agent authority for delegation decisions
3. Auditing agent behavior for governance compliance
4. Onboarding new agents with similar responsibilities

## Regenerating This Index

```bash
./scripts/generate-standing-orders-index.sh
```

---

*Auto-generated by PAI governance tooling*
FOOTER

echo -e "${GREEN}Generated: $OUTPUT_FILE${NC}"
echo -e "Total agents processed: ${YELLOW}$IDENTITY_COUNT${NC}"
