#!/bin/bash
# LICH'S PHYLACTERY - Schema Soul Preservation
#
# In D&D, a lich stores its soul in a phylactery so it can resurrect.
# This hook stores the database's soul (schema) so it can be resurrected.
#
# Triggers on:
#   - Alembic migrations (backend/alembic/versions/*.py)
#   - SQLAlchemy models (backend/app/models/*.py)
#
# Output: backend/schema.sql (auto-staged for commit)
# Contains NO DATA - just structure. Safe to commit. Sacred timeline preserved.

set -euo pipefail

SCHEMA_FILE="backend/schema.sql"
COMPOSE_FILE="${COMPOSE_FILE:-docker-compose.local.yml}"

# Check if any DB-related files are staged
STAGED_FILES=$(git diff --cached --name-only 2>/dev/null || echo "")

HAS_MIGRATIONS=$(echo "$STAGED_FILES" | grep -E '^backend/alembic/versions/.*\.py$' || true)
HAS_MODELS=$(echo "$STAGED_FILES" | grep -E '^backend/app/models/.*\.py$' || true)

if [[ -z "$HAS_MIGRATIONS" && -z "$HAS_MODELS" ]]; then
    # No DB changes, skip
    exit 0
fi

echo "💀 DB structure changes detected, preserving soul in phylactery..."

# Check if database is available (Docker or native)
DOCKER_DB_RUNNING=false
if docker compose -f "$COMPOSE_FILE" ps db --status running 2>/dev/null | grep -q "running"; then
    DOCKER_DB_RUNNING=true
fi

NATIVE_DB_RUNNING=false
if pg_isready -q -h localhost -p 5432 2>/dev/null; then
    NATIVE_DB_RUNNING=true
fi

if [ "$DOCKER_DB_RUNNING" = false ] && [ "$NATIVE_DB_RUNNING" = false ]; then
    echo "Warning: No database available, skipping schema snapshot"
    exit 0
fi

# Dump schema (no data)
if [ "$DOCKER_DB_RUNNING" = true ]; then
    docker compose -f "$COMPOSE_FILE" exec -T db \
      pg_dump -U scheduler --schema-only residency_scheduler > "$SCHEMA_FILE.tmp" 2>/dev/null
else
    pg_dump -h localhost -p 5432 -U scheduler --schema-only residency_scheduler > "$SCHEMA_FILE.tmp" 2>/dev/null
fi

if [[ ! -s "$SCHEMA_FILE.tmp" ]]; then
    echo "⚠️  Schema dump empty, skipping (migrations may not be applied yet)"
    rm -f "$SCHEMA_FILE.tmp"
    exit 0
fi

# Add header
{
    echo "-- ╔═══════════════════════════════════════════════════════════════╗"
    echo "-- ║            LICH'S PHYLACTERY - Database Soul                  ║"
    echo "-- ╚═══════════════════════════════════════════════════════════════╝"
    echo "--"
    echo "-- Generated: $(date -u +%Y-%m-%dT%H:%M:%SZ)"
    echo "-- Branch: $(git branch --show-current 2>/dev/null || echo 'unknown')"
    echo "-- Commit: $(git rev-parse --short HEAD 2>/dev/null || echo 'pending')"
    echo "--"
    echo "-- AUTO-GENERATED by Lich's Phylactery pre-commit hook"
    echo "-- Contains NO DATA - just structure. The soul, not the flesh."
    echo "-- Safe to commit. Sacred timeline preserved."
    echo ""
    cat "$SCHEMA_FILE.tmp"
} > "$SCHEMA_FILE"
rm -f "$SCHEMA_FILE.tmp"

# Stats
TABLES=$(grep -c "CREATE TABLE" "$SCHEMA_FILE" || echo 0)
INDEXES=$(grep -c "CREATE INDEX" "$SCHEMA_FILE" || echo 0)

echo "💀 Phylactery preserved: $TABLES tables, $INDEXES indexes"
echo "   The lich may now resurrect."

# Auto-stage the schema file
git add "$SCHEMA_FILE"
echo "   Bound $SCHEMA_FILE to commit"
